// Package domain holds the core entities and ports of the ingestion gateway.
//
// This is the innermost layer of the Clean Architecture: it must not import
// any transport (net/http), broker (kafka) or storage package, so that the
// business rules stay independent of the delivery and infrastructure details.
package domain

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"time"
)

// Validation errors returned by Event.Validate. Callers (e.g. the HTTP
// delivery layer) match on these with errors.Is to map them to a 400 response.
var (
	// ErrMissingSource is returned when the event has no originating system.
	ErrMissingSource = errors.New("source is required")
	// ErrMissingEventType is returned when the event carries no type.
	ErrMissingEventType = errors.New("event_type is required")
	// ErrMissingPayload is returned when the event body is empty.
	ErrMissingPayload = errors.New("payload must not be empty")
)

// Event is the core entity of the platform: a single fact emitted by an
// external source that the gateway accepts and forwards to the stream.
type Event struct {
	// ID uniquely identifies the event. Generated by the gateway when the
	// producer of the request does not supply one.
	ID string
	// Source names the system that emitted the event (e.g. "checkout-api").
	Source string
	// EventType classifies the event (e.g. "order.created").
	EventType string
	// Payload is the free-form body of the event.
	Payload map[string]any
	// Timestamp is when the event occurred, always stored in UTC.
	Timestamp time.Time
}

// NewEvent builds a validated Event, filling in the fields the gateway owns.
//
// An empty id gets a freshly generated identifier and a zero ts falls back to
// the current time, so callers may omit both. The returned error is one of the
// Err* values in this package when the event is not acceptable.
func NewEvent(id, source, eventType string, payload map[string]any, ts time.Time) (Event, error) {
	if id == "" {
		generated, err := newID()
		if err != nil {
			return Event{}, err
		}
		id = generated
	}

	if ts.IsZero() {
		ts = time.Now()
	}

	e := Event{
		ID:        id,
		Source:    source,
		EventType: eventType,
		Payload:   payload,
		Timestamp: ts.UTC(),
	}

	if err := e.Validate(); err != nil {
		return Event{}, err
	}

	return e, nil
}

// Validate enforces the invariants every accepted event must satisfy.
func (e Event) Validate() error {
	switch {
	case e.Source == "":
		return ErrMissingSource
	case e.EventType == "":
		return ErrMissingEventType
	case len(e.Payload) == 0:
		return ErrMissingPayload
	default:
		return nil
	}
}

// newID returns a random 128-bit identifier as a hex string. It avoids an
// external UUID dependency while remaining collision-safe in practice.
func newID() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}

	return hex.EncodeToString(b[:]), nil
}
