{{- if and .Values.image.registryUsername .Values.image.registryPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eventpulse.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.registry .Values.image.registryUsername .Values.image.registryPassword (printf "%s:%s" .Values.image.registryUsername .Values.image.registryPassword | b64enc) | b64enc | quote }}
{{- end }}