{{- if or .Values.embeddings.huggingfaceToken .Values.embeddings.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mcpName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eventpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.embeddings.huggingfaceToken }}
  huggingface-token: {{ .Values.embeddings.huggingfaceToken | quote }}
  {{- end }}
  {{- if .Values.embeddings.openaiApiKey }}
  openai-api-key: {{ .Values.embeddings.openaiApiKey | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgresName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eventpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.postgres.user | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}