apiVersion: v1
kind: Service
metadata:
  name: metrics-aggregator-nodeport
  namespace: eventpulse
  labels:
    app.kubernetes.io/part-of: eventpulse
    app.kubernetes.io/component: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: eventpulse
    app.kubernetes.io/name: metrics-aggregator
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      nodePort: 30090